In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [25]:
heart_data=pd.read_csv('heart.csv')
heart_data.head()

,Age,Sex,Chest P,BP,Chol,FBS,EKG,Max HR,Ex angina,ST dep,Slope,fluro,Thal,target
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence

In [28]:
heart_data['Thal'].unique()

array([3, 7, 6], dtype=int64)

In [26]:
heart_data.tail()

,Age,Sex,Chest P,BP,Chol,FBS,EKG,Max HR,Ex angina,ST dep,Slope,fluro,Thal,target
265,52,1,3,172,199,1,0,162,0,0.5,1,0,7,Absence
266,44,1,2,120,263,0,0,173,0,0.0,1,0,7,Absence
267,56,0,2,140,294,0,2,153,0,1.3,2,0,3,Absence
268,57,1,4,140,192,0,0,148,0,0.4,2,0,6,Absence
269,67,1,4,160,286,0,2,108,1,1.5,2,3,3,Presence

In [29]:
heart_data.shape

(270, 14)

In [30]:
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        270 non-null    int64
 1   Sex        270 non-null    int64
 2   Chest P    270 non-null    int64
 3   BP         270 non-null    int64
 4   Chol       270 non-null    int64
 5   FBS        270 non-null    int64
 6   EKG        270 non-null    int64
 7   Max HR     270 non-null    int64
 8   Ex angina  270 non-null    int64
 9   ST dep     270 non-null    float64
 10  Slope      270 non-null    int64
 11   fluro     270 non-null    int64
 12  Thal       270 non-null    int64
 13  target     270 non-null    object
dtypes: float64(1), int64(12), object(1)
memory usage: 29.7+ KB

In [35]:
le=LabelEncoder()
cols=['target']
for f in cols:
    heart_data[f]=le.fit_transform(heart_data[f])

In [36]:
heart_data.head()

,Age,Sex,Chest P,BP,Chol,FBS,EKG,Max HR,Ex angina,ST dep,Slope,fluro,Thal,target
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,1
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,0
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,1
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,0
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,0

In [9]:
heart_data.isnull().sum()

Age                        0
Sex                        0
Chest pain type            0
BP                         0
Cholesterol                0
FBS over 120               0
EKG results                0
Max HR                     0
Exercise angina            0
ST depression              0
Slope of ST                0
Number of vessels fluro    0
Thallium                   0
Heart Disease              0
dtype: int64

In [37]:
heart_data.describe().transpose()

           count        mean        std    min    25%    50%    75%    max
Age        270.0   54.433333   9.109067   29.0   48.0   55.0   61.0   77.0
Sex        270.0    0.677778   0.468195    0.0    0.0    1.0    1.0    1.0
Chest P    270.0    3.174074   0.950090    1.0    3.0    3.0    4.0    4.0
BP         270.0  131.344444  17.861608   94.0  120.0  130.0  140.0  200.0
Chol       270.0  249.659259  51.686237  126.0  213.0  245.0  280.0  564.0
FBS        270.0    0.148148   0.355906    0.0    0.0    0.0    0.0    1.0
EKG        270.0    1.022222   0.997891    0.0    0.0    2.0    2.0    2.0
Max HR     270.0  149.677778  23.165717   71.0  133.0  153.5  166.0  202.0
Ex angina  270.0    0.329630   0.470952    0.0    0.0    0.0    1.0    1.0
ST dep     270.0    1.050000   1.145210    0.0    0.0    0.8    1.6    6.2
Slope      270.0    1.585185   0.614390    1.0    1.0    2.0    2.0    3.0
 fluro     270.0    0.670370   0.943896    0.0    0.0    0.0    1.0    3.0
Thal       270.0    4.696296   1.940659    3.0    3.0    3.0    7.0    7.0
target     270.0    0.444444   0.497827    0.0    0.0    0.0    1.0    1.0

In [12]:
#Splitting the Features and Target
x = heart_data.drop(columns='Heart Disease',axis=1)
y = heart_data['Heart Disease']

In [13]:
print(x)

     Age  Sex  Chest pain type   BP  Cholesterol  FBS over 120  EKG results  \
0     70    1                4  130          322             0            2
1     67    0                3  115          564             0            2
2     57    1                2  124          261             0            0
3     64    1                4  128          263             0            0
4     74    0                2  120          269             0            2
..   ...  ...              ...  ...          ...           ...          ...
265   52    1                3  172          199             1            0
266   44    1                2  120          263             0            0
267   56    0                2  140          294             0            2
268   57    1                4  140          192             0            0
269   67    1                4  160          286             0            2

     Max HR  Exercise angina  ST depression  Slope of ST  \
0       109                0            2.4            2
1       160                0            1.6            2
2       141                0            0.3            1
3       105                1            0.2            2
4       121                1            0.2            1
..      ...              ...            ...          ...
265     162                0            0.5            1
266     173                0            0.0            1
267     153                0            1.3            2
268     148                0            0.4            2
269     108                1            1.5            2

     Number of vessels fluro  Thallium
0                          3         3
1                          0         7
2                          0         7
3                          1         7
4                          1         3
..                       ...       ...
265                        0         7
266                        0         7
267                        0         3
268                        0         6
269                        3         3

[270 rows x 13 columns]

In [14]:
print(y)

0      1
1      0
2      1
3      0
4      0
      ..
265    0
266    0
267    0
268    0
269    1
Name: Heart Disease, Length: 270, dtype: int32

In [15]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state =1, shuffle = True)

In [16]:
print(x.shape,x_train.shape,x_test.shape)

(270, 13) (216, 13) (54, 13)

In [17]:
model=LogisticRegression()

In [18]:
#Training the LogisticRegression model wiht Training model
model.fit(x_train,y_train)

C:\Users\nssbh\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [19]:
#Accuracy on Training data
x_train_prediction=model.predict(x_train)
training_data_accuracy=accuracy_score(x_train_prediction,y_train)

In [20]:
print("Accuracy on Training data : ",training_data_accuracy)

Accuracy on Training data :  0.8611111111111112

In [21]:
#Accuracy on Test data
x_test_prediction = model.predict(x_test)
test_data_accuracy= accuracy_score(x_test_prediction,y_test)

In [22]:
print("Accuracy on Test data : ",test_data_accuracy)

Accuracy on Test data :  0.8333333333333334

In [23]:
#Building a Predictive System
input_data=(62,0,0,140,268,0,0,160,0,3.6,0,2,2)

#Change the input data to a numpy array
input_data_as_numpy_array= np.asarray(input_data)

#Reshape the numpy array as we are predicting for only on instance
input_data_reshaped= input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)

if(prediction[0]==0):
    print("The person does not have a Heart Disease")
else:
    print("**This Person has heart disease **")

The person does not have a Heart Disease

C:\Users\nssbh\AppData\Roaming\Python\Python310\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [24]:
import joblib

joblib.dump(model, 'model.joblib')

['model.joblib']